---
output: html
---




```{r}
library(tidyverse)
```



```{r}
df <- read_csv("https://figshare.com/ndownloader/files/7012670")
lpi <- df |>
  pivot_longer(matches("\\d{4}"),
                       names_to="year",
                       values_to="abundance") |>
  mutate(abundance= as.numeric(abundance)) |>
  filter(!is.na(abundance)) |>
  mutate(year = as.integer(year))
lpi

# years of data in each study
lpi |> count(ID, sort=TRUE) |> pull(n) |> hist()

lpi |> count(year,Class) |>
  ggplot(aes(year, n)) + geom_col(aes(fill=Class))
```
```{r}
#download.file("https://biotime.st-andrews.ac.uk/downloads/BioTIMEQuery_24_06_2021.zip", "biotime.zip")
#archive::archive_extract("biotime.zip")
#biotime <- read_csv("BioTIMEQuery_24_06_2021.csv")
#biotime <- arrow::write_parquet(biotime, "biotime_2021.parquet")

biotime <- arrow::open_dataset("biotime_2021.parquet")


biotime |> count(YEAR, STUDY_ID) |> collect() |>
  ggplot(aes(YEAR, n)) + geom_col(aes(fill=STUDY_ID),position="stack") + scale_fill_viridis_c()

s```

```{r}
sp <- biotime |> distinct(GENUS_SPECIES) |> pull(GENUS_SPECIES)
library(taxadb)
col <- taxadb::taxa_tbl("col")
col_matches <- col |> filter(scientificName %in% sp) |> collect()
biotime %>% distinct(GENUS, SPECIES)|> collect() -> x
col_matches_sp <- col |> inner_join(x, copy=TRUE) |> collect()
col_matches_sp
biotime |> rename(genus=GENUS, specificEpithet=SPECIES) |> collect() |> left_join(col_matches_sp, copy=TRUE) |> count(YEAR, kingdom) |>  ggplot(aes(YEAR, n, fill=kingdom)) + geom_col()
```




```{r}
trees <- biotime |> filter(STUDY_ID == 10) |> collect()
trees <- trees |> mutate(control = grepl("Control", SAMPLE_DESC))
trees |> count(PLOT)

trees |> group_by(GENUS_SPECIES, YEAR, control) |> summarise(count = sum(sum.allrawdata.ABUNDANCE), .groups="drop") |>
  ggplot(aes(YEAR, count, col=GENUS_SPECIES)) + geom_point() + geom_line() + scale_y_log10() + facet_wrap(~control)
```

